name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Required for creating releases
  actions: read

jobs:
  build-and-release:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Get version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="dev-$(git rev-parse --short HEAD)"
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        
    - name: Update version in script
      run: |
        sed -i '' 's/VERSION="1.0.0"/VERSION="${{ steps.get_version.outputs.version }}"/' create-dmg.sh
        
    - name: Build and create DMG
      run: |
        ./create-dmg.sh
        
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: KeyBoy-${{ steps.get_version.outputs.version }}-dmg
        path: KeyBoy.dmg
        
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: KeyBoy.dmg
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}